version: 2
jobs:
  build:
    docker:
      - image: node:12-alpine
    steps:
      - checkout
      - run: pwd && ls -la
      - run: node -v
      - run: apk add tar ca-certificates
      - run:
          name: copy config
          command: cp src/config/config.example.js src/config/config.js
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Production build
          command: CI=false yarn build
      - run:
          name: create tar from build
          command: tar cvf build.tar build
      - store_artifacts:
          path: build.tar

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
