/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { ServiceClientOptions } from "@azure/ms-rest-js";
import * as msRest from "@azure/ms-rest-js";

/**
 * An interface representing User.
 */
export interface User {
  guid?: string;
  login?: string;
  email?: string;
  registerDate?: string;
}

/**
 * An interface representing ExternalRepoOwner.
 */
export interface ExternalRepoOwner {
  login?: string;
}

/**
 * An interface representing ExternalRepo.
 */
export interface ExternalRepo {
  originId?: string;
  fullName?: string;
  description?: string;
  /**
   * Possible values include: 'GitHub', 'GitLab'
   */
  serviceType?: ServiceType;
  owner?: ExternalRepoOwner;
}

/**
 * An interface representing Project.
 */
export interface Project {
  guid?: string;
  name?: string;
  description?: string;
  repositoryGuid?: string;
  creatorGuid?: string;
  baseUri?: string;
  starsCount?: number;
  createdAt?: string;
  updatedAt?: string;
}

/**
 * An interface representing Repository.
 */
export interface Repository {
  guid?: string;
  creator?: User;
  title?: string;
  repoUrl?: string;
  originId?: string;
  createdAt?: string;
}

/**
 * An interface representing Board.
 */
export interface Board {
  guid?: string;
  name?: string;
  description?: string;
  projectGuid?: string;
  userGuid?: string;
  createdAt?: string;
  updatedAt?: string;
}

/**
 * An interface representing Column.
 */
export interface Column {
  guid?: string;
  name?: string;
  boardGuid?: string;
  boardOrder?: number;
}

/**
 * An interface representing Card.
 */
export interface Card {
  guid?: string;
  name?: string;
  description?: string;
  creatorGuid?: string;
  columnOrder?: number;
  columnGuid?: string;
  createdAt?: string;
  updatedAt?: string;
}

/**
 * An interface representing ProjectWorkType.
 */
export interface ProjectWorkType {
  guid?: string;
  projectGuid?: string;
  title?: string;
  budgetPercent?: number;
  createdAt?: string;
  updatedAt?: string;
}

/**
 * An interface representing CardWork.
 */
export interface CardWork {
  guid?: string;
  userGuid?: string;
  cardGuid?: string;
  workType?: ProjectWorkType;
  proof?: string;
  createdAt?: string;
  updatedAt?: string;
}

/**
 * An interface representing FundingBalance.
 */
export interface FundingBalance {
  guid?: string;
  entityGuid?: string;
  /**
   * Possible values include: 'ProjectCategory', 'Project', 'Board', 'Card', 'BacklogItem',
   * 'UserBalance', 'User', 'ProjectProductPurchase', 'BoardColumn'
   */
  entityType?: EntityType;
  amount?: number;
  /**
   * Possible values include: 'Usd', 'BitCoin', 'Ethereum', 'Erc20Token', 'Waves', 'WavesToken',
   * 'LiteCoin'
   */
  currencyType?: CurrencyType;
}

/**
 * An interface representing CurrencyWallet.
 */
export interface CurrencyWallet {
  guid?: string;
  address?: string;
  /**
   * Possible values include: 'Usd', 'BitCoin', 'Ethereum', 'Erc20Token', 'Waves', 'WavesToken',
   * 'LiteCoin'
   */
  currencyType?: CurrencyType1;
}

/**
 * An interface representing Invoice.
 */
export interface Invoice {
  guid?: string;
  userId?: string;
  entityGuid?: string;
  /**
   * Possible values include: 'ProjectCategory', 'Project', 'Board', 'Card', 'BacklogItem',
   * 'UserBalance', 'User', 'ProjectProductPurchase', 'BoardColumn'
   */
  entityType?: EntityType1;
  amount?: number;
  /**
   * Possible values include: 'Usd', 'BitCoin', 'Ethereum', 'Erc20Token', 'Waves', 'WavesToken',
   * 'LiteCoin'
   */
  currencyType?: CurrencyType2;
  wallet?: CurrencyWallet;
  createdAt?: string;
  updatedAt?: string;
}

/**
 * An interface representing UserBalance.
 */
export interface UserBalance {
  guid?: string;
  userGuid?: string;
  /**
   * Possible values include: 'Usd', 'BitCoin', 'Ethereum', 'Erc20Token', 'Waves', 'WavesToken',
   * 'LiteCoin'
   */
  currencyType?: CurrencyType3;
  amount?: number;
  createdAt?: string;
  updatedAt?: string;
}

/**
 * An interface representing UserSetting.
 */
export interface UserSetting {
  guid?: string;
  userGuid?: string;
  key?: string;
  value?: string;
}

/**
 * An interface representing LibraryItem.
 */
export interface LibraryItem {
  guid?: string;
  userGuid?: string;
  projectGuid?: string;
  createdAt?: string;
}

/**
 * An interface representing ProjectProduct.
 */
export interface ProjectProduct {
  guid?: string;
  name?: string;
  description?: string;
  /**
   * url to view product info (optional)
   */
  url?: string;
  projectGuid?: string;
  usdPrice?: number;
  durationHours?: number;
  createdAt?: string;
  updatedAt?: string;
}

/**
 * An interface representing GetLoginOKResponseData.
 */
export interface GetLoginOKResponseData {
  token?: string;
}

/**
 * An interface representing GetLoginOKResponse.
 */
export interface GetLoginOKResponse {
  data?: GetLoginOKResponseData;
}

/**
 * An interface representing PostRegisterOKResponseData.
 */
export interface PostRegisterOKResponseData {
  response?: string;
}

/**
 * An interface representing PostRegisterOKResponse.
 */
export interface PostRegisterOKResponse {
  data?: PostRegisterOKResponseData;
}

/**
 * An interface representing PostConfirmEmailOKResponseData.
 */
export interface PostConfirmEmailOKResponseData {
  token?: string;
}

/**
 * An interface representing PostConfirmEmailOKResponse.
 */
export interface PostConfirmEmailOKResponse {
  data?: PostConfirmEmailOKResponseData;
}

/**
 * An interface representing GetGitHubLoginLinkOKResponseData.
 */
export interface GetGitHubLoginLinkOKResponseData {
  loginLink?: string;
}

/**
 * An interface representing GetGitHubLoginLinkOKResponse.
 */
export interface GetGitHubLoginLinkOKResponse {
  data?: GetGitHubLoginLinkOKResponseData;
}

/**
 * An interface representing GetGitHubAuthTokenOKResponseData.
 */
export interface GetGitHubAuthTokenOKResponseData {
  token?: string;
}

/**
 * An interface representing GetGitHubAuthTokenOKResponse.
 */
export interface GetGitHubAuthTokenOKResponse {
  data?: GetGitHubAuthTokenOKResponseData;
}

/**
 * An interface representing GetGitLabLoginLinkOKResponseData.
 */
export interface GetGitLabLoginLinkOKResponseData {
  loginLink?: string;
}

/**
 * An interface representing GetGitLabLoginLinkOKResponse.
 */
export interface GetGitLabLoginLinkOKResponse {
  data?: GetGitLabLoginLinkOKResponseData;
}

/**
 * An interface representing GetGitLabAuthTokenOKResponseData.
 */
export interface GetGitLabAuthTokenOKResponseData {
  token?: string;
}

/**
 * An interface representing GetGitLabAuthTokenOKResponse.
 */
export interface GetGitLabAuthTokenOKResponse {
  data?: GetGitLabAuthTokenOKResponseData;
}

/**
 * An interface representing GetMeExternalRepositoriesOKResponseData.
 */
export interface GetMeExternalRepositoriesOKResponseData {
  repositories?: ExternalRepo[];
}

/**
 * An interface representing GetMeExternalRepositoriesOKResponse.
 */
export interface GetMeExternalRepositoriesOKResponse {
  data?: GetMeExternalRepositoriesOKResponseData;
}

/**
 * An interface representing GetMyIntegrationsStatusOKResponseDataIntegrationsGithubUser.
 */
export interface GetMyIntegrationsStatusOKResponseDataIntegrationsGithubUser {
  email?: string;
  login?: string;
}

/**
 * An interface representing GetMyIntegrationsStatusOKResponseDataIntegrationsGithub.
 */
export interface GetMyIntegrationsStatusOKResponseDataIntegrationsGithub {
  connected?: boolean;
  user?: GetMyIntegrationsStatusOKResponseDataIntegrationsGithubUser;
}

/**
 * An interface representing GetMyIntegrationsStatusOKResponseDataIntegrationsGitlabUser.
 */
export interface GetMyIntegrationsStatusOKResponseDataIntegrationsGitlabUser {
  email?: string;
  login?: string;
}

/**
 * An interface representing GetMyIntegrationsStatusOKResponseDataIntegrationsGitlab.
 */
export interface GetMyIntegrationsStatusOKResponseDataIntegrationsGitlab {
  connected?: boolean;
  user?: GetMyIntegrationsStatusOKResponseDataIntegrationsGitlabUser;
}

/**
 * An interface representing GetMyIntegrationsStatusOKResponseDataIntegrations.
 */
export interface GetMyIntegrationsStatusOKResponseDataIntegrations {
  github?: GetMyIntegrationsStatusOKResponseDataIntegrationsGithub;
  gitlab?: GetMyIntegrationsStatusOKResponseDataIntegrationsGitlab;
}

/**
 * An interface representing GetMyIntegrationsStatusOKResponseData.
 */
export interface GetMyIntegrationsStatusOKResponseData {
  integrations?: GetMyIntegrationsStatusOKResponseDataIntegrations;
}

/**
 * An interface representing GetMyIntegrationsStatusOKResponse.
 */
export interface GetMyIntegrationsStatusOKResponse {
  data?: GetMyIntegrationsStatusOKResponseData;
}

/**
 * An interface representing PostImportRepositoryOKResponseData.
 */
export interface PostImportRepositoryOKResponseData {
  project?: Project;
  repository?: Repository;
}

/**
 * An interface representing PostImportRepositoryOKResponse.
 */
export interface PostImportRepositoryOKResponse {
  data?: PostImportRepositoryOKResponseData;
}

/**
 * An interface representing GetRepoOKResponseData.
 */
export interface GetRepoOKResponseData {
  repository?: Repository;
}

/**
 * An interface representing GetRepoOKResponse.
 */
export interface GetRepoOKResponse {
  data?: GetRepoOKResponseData;
}

/**
 * An interface representing GetProjectOKResponseData.
 */
export interface GetProjectOKResponseData {
  project?: Project;
}

/**
 * An interface representing GetProjectOKResponse.
 */
export interface GetProjectOKResponse {
  data?: GetProjectOKResponseData;
}

/**
 * An interface representing EditProjectOKResponseData.
 */
export interface EditProjectOKResponseData {
  project?: Project;
}

/**
 * An interface representing EditProjectOKResponse.
 */
export interface EditProjectOKResponse {
  data?: EditProjectOKResponseData;
}

/**
 * An interface representing GetProjectBoardsOKResponseData.
 */
export interface GetProjectBoardsOKResponseData {
  boards?: Board[];
}

/**
 * An interface representing GetProjectBoardsOKResponse.
 */
export interface GetProjectBoardsOKResponse {
  data?: GetProjectBoardsOKResponseData;
}

/**
 * An interface representing GetBoardOKResponseData.
 */
export interface GetBoardOKResponseData {
  board?: Board;
}

/**
 * An interface representing GetBoardOKResponse.
 */
export interface GetBoardOKResponse {
  data?: GetBoardOKResponseData;
}

/**
 * An interface representing GetBoardColumnsOKResponseData.
 */
export interface GetBoardColumnsOKResponseData {
  columns?: Column[];
}

/**
 * An interface representing GetBoardColumnsOKResponse.
 */
export interface GetBoardColumnsOKResponse {
  data?: GetBoardColumnsOKResponseData;
}

/**
 * An interface representing GetColumnCardsOKResponseData.
 */
export interface GetColumnCardsOKResponseData {
  cards?: Card[];
}

/**
 * An interface representing GetColumnCardsOKResponse.
 */
export interface GetColumnCardsOKResponse {
  data?: GetColumnCardsOKResponseData;
}

/**
 * An interface representing GetProjectByAliasOKResponseData.
 */
export interface GetProjectByAliasOKResponseData {
  project?: Project;
}

/**
 * An interface representing GetProjectByAliasOKResponse.
 */
export interface GetProjectByAliasOKResponse {
  data?: GetProjectByAliasOKResponseData;
}

/**
 * An interface representing CreateCardCreatedResponseData.
 */
export interface CreateCardCreatedResponseData {
  card?: Card;
}

/**
 * An interface representing CreateCardCreatedResponse.
 */
export interface CreateCardCreatedResponse {
  data?: CreateCardCreatedResponseData;
}

/**
 * An interface representing EditCardOKResponseData.
 */
export interface EditCardOKResponseData {
  card?: Card;
}

/**
 * An interface representing EditCardOKResponse.
 */
export interface EditCardOKResponse {
  data?: EditCardOKResponseData;
}

/**
 * An interface representing GetCardWorkOKResponseData.
 */
export interface GetCardWorkOKResponseData {
  project?: CardWork;
}

/**
 * An interface representing GetCardWorkOKResponse.
 */
export interface GetCardWorkOKResponse {
  data?: GetCardWorkOKResponseData;
}

/**
 * An interface representing GetEntityFundingBalancesOKResponseData.
 */
export interface GetEntityFundingBalancesOKResponseData {
  balances?: FundingBalance;
}

/**
 * An interface representing GetEntityFundingBalancesOKResponse.
 */
export interface GetEntityFundingBalancesOKResponse {
  data?: GetEntityFundingBalancesOKResponseData;
}

/**
 * An interface representing GetCardProjectOKResponseData.
 */
export interface GetCardProjectOKResponseData {
  project?: Project;
}

/**
 * An interface representing GetCardProjectOKResponse.
 */
export interface GetCardProjectOKResponse {
  data?: GetCardProjectOKResponseData;
}

/**
 * An interface representing GetProjectWorkTypesOKResponseData.
 */
export interface GetProjectWorkTypesOKResponseData {
  workTypes?: ProjectWorkType[];
}

/**
 * An interface representing GetProjectWorkTypesOKResponse.
 */
export interface GetProjectWorkTypesOKResponse {
  data?: GetProjectWorkTypesOKResponseData;
}

/**
 * An interface representing PostSubmitCardWorkOKResponseData.
 */
export interface PostSubmitCardWorkOKResponseData {
  workItem?: ProjectWorkType;
}

/**
 * An interface representing PostSubmitCardWorkOKResponse.
 */
export interface PostSubmitCardWorkOKResponse {
  data?: PostSubmitCardWorkOKResponseData;
}

/**
 * An interface representing PostInvoiceCreatedResponseData.
 */
export interface PostInvoiceCreatedResponseData {
  invoice?: Invoice;
}

/**
 * An interface representing PostInvoiceCreatedResponse.
 */
export interface PostInvoiceCreatedResponse {
  data?: PostInvoiceCreatedResponseData;
}

/**
 * An interface representing GetMyInvoiceOKResponseData.
 */
export interface GetMyInvoiceOKResponseData {
  invoice?: Invoice;
}

/**
 * An interface representing GetMyInvoiceOKResponse.
 */
export interface GetMyInvoiceOKResponse {
  data?: GetMyInvoiceOKResponseData;
}

/**
 * An interface representing GetMyActiveInvoicesOKResponseData.
 */
export interface GetMyActiveInvoicesOKResponseData {
  invoices?: Invoice[];
}

/**
 * An interface representing GetMyActiveInvoicesOKResponse.
 */
export interface GetMyActiveInvoicesOKResponse {
  data?: GetMyActiveInvoicesOKResponseData;
}

/**
 * An interface representing GetMyFinishedInvoicesOKResponseData.
 */
export interface GetMyFinishedInvoicesOKResponseData {
  invoices?: Invoice[];
}

/**
 * An interface representing GetMyFinishedInvoicesOKResponse.
 */
export interface GetMyFinishedInvoicesOKResponse {
  data?: GetMyFinishedInvoicesOKResponseData;
}

/**
 * An interface representing PatchMyInvoiceOKResponseData.
 */
export interface PatchMyInvoiceOKResponseData {
  invoices?: Invoice[];
}

/**
 * An interface representing PatchMyInvoiceOKResponse.
 */
export interface PatchMyInvoiceOKResponse {
  data?: PatchMyInvoiceOKResponseData;
}

/**
 * An interface representing GetMyBalancesOKResponseData.
 */
export interface GetMyBalancesOKResponseData {
  balances?: UserBalance[];
}

/**
 * An interface representing GetMyBalancesOKResponse.
 */
export interface GetMyBalancesOKResponse {
  data?: GetMyBalancesOKResponseData;
}

/**
 * An interface representing GetMySettingOKResponseData.
 */
export interface GetMySettingOKResponseData {
  setting?: UserSetting;
}

/**
 * An interface representing GetMySettingOKResponse.
 */
export interface GetMySettingOKResponse {
  data?: GetMySettingOKResponseData;
}

/**
 * An interface representing SetMySettingOKResponseData.
 */
export interface SetMySettingOKResponseData {
  setting?: UserSetting;
}

/**
 * An interface representing SetMySettingOKResponse.
 */
export interface SetMySettingOKResponse {
  data?: SetMySettingOKResponseData;
}

/**
 * An interface representing GetMyLibraryProjectsOKResponseData.
 */
export interface GetMyLibraryProjectsOKResponseData {
  libraryProjects?: LibraryItem[];
}

/**
 * An interface representing GetMyLibraryProjectsOKResponse.
 */
export interface GetMyLibraryProjectsOKResponse {
  data?: GetMyLibraryProjectsOKResponseData;
}

/**
 * An interface representing AddProjectToMyLibraryCreatedResponseData.
 */
export interface AddProjectToMyLibraryCreatedResponseData {
  libraryProject?: LibraryItem;
}

/**
 * An interface representing AddProjectToMyLibraryCreatedResponse.
 */
export interface AddProjectToMyLibraryCreatedResponse {
  data?: AddProjectToMyLibraryCreatedResponseData;
}

/**
 * An interface representing RemoveProjectFromMyLibraryOKResponseData.
 */
export interface RemoveProjectFromMyLibraryOKResponseData {
  libraryProject?: LibraryItem;
}

/**
 * An interface representing RemoveProjectFromMyLibraryOKResponse.
 */
export interface RemoveProjectFromMyLibraryOKResponse {
  data?: RemoveProjectFromMyLibraryOKResponseData;
}

/**
 * An interface representing GetMyLibraryProjectStatusOKResponseDataStatus.
 */
export interface GetMyLibraryProjectStatusOKResponseDataStatus {
  inLibrary?: boolean;
}

/**
 * An interface representing GetMyLibraryProjectStatusOKResponseData.
 */
export interface GetMyLibraryProjectStatusOKResponseData {
  status?: GetMyLibraryProjectStatusOKResponseDataStatus;
}

/**
 * An interface representing GetMyLibraryProjectStatusOKResponse.
 */
export interface GetMyLibraryProjectStatusOKResponse {
  data?: GetMyLibraryProjectStatusOKResponseData;
}

/**
 * An interface representing GetMeOKResponseData.
 */
export interface GetMeOKResponseData {
  me?: User[];
}

/**
 * An interface representing GetMeOKResponse.
 */
export interface GetMeOKResponse {
  data?: GetMeOKResponseData;
}

/**
 * An interface representing GetUserOKResponseData.
 */
export interface GetUserOKResponseData {
  user?: User[];
}

/**
 * An interface representing GetUserOKResponse.
 */
export interface GetUserOKResponse {
  data?: GetUserOKResponseData;
}

/**
 * An interface representing LoginViaFacebookOKResponseData.
 */
export interface LoginViaFacebookOKResponseData {
  token?: string;
}

/**
 * An interface representing LoginViaFacebookOKResponse.
 */
export interface LoginViaFacebookOKResponse {
  data?: LoginViaFacebookOKResponseData;
}

/**
 * An interface representing LoginViaGoogleOKResponseData.
 */
export interface LoginViaGoogleOKResponseData {
  token?: string;
}

/**
 * An interface representing LoginViaGoogleOKResponse.
 */
export interface LoginViaGoogleOKResponse {
  data?: LoginViaGoogleOKResponseData;
}

/**
 * An interface representing GetMyEntityPermissionsOKResponseData.
 */
export interface GetMyEntityPermissionsOKResponseData {
  permissions?: string[];
}

/**
 * An interface representing GetMyEntityPermissionsOKResponse.
 */
export interface GetMyEntityPermissionsOKResponse {
  data?: GetMyEntityPermissionsOKResponseData;
}

/**
 * An interface representing GetNewestProjectsOKResponseData.
 */
export interface GetNewestProjectsOKResponseData {
  projects?: Project[];
}

/**
 * An interface representing GetNewestProjectsOKResponse.
 */
export interface GetNewestProjectsOKResponse {
  data?: GetNewestProjectsOKResponseData;
}

/**
 * An interface representing GetRandomProjectsOKResponseData.
 */
export interface GetRandomProjectsOKResponseData {
  projects?: Project[];
}

/**
 * An interface representing GetRandomProjectsOKResponse.
 */
export interface GetRandomProjectsOKResponse {
  data?: GetRandomProjectsOKResponseData;
}

/**
 * An interface representing GetProjectProductsOKResponseData.
 */
export interface GetProjectProductsOKResponseData {
  products?: ProjectProduct[];
}

/**
 * An interface representing GetProjectProductsOKResponse.
 */
export interface GetProjectProductsOKResponse {
  data?: GetProjectProductsOKResponseData;
}

/**
 * An interface representing SupportHubApiOptions.
 */
export interface SupportHubApiOptions extends ServiceClientOptions {
  baseUri?: string;
}

/**
 * Optional Parameters.
 */
export interface SupportHubApiGetLoginOptionalParams extends msRest.RequestOptionsBase {
  email?: string;
  password?: string;
}

/**
 * Optional Parameters.
 */
export interface SupportHubApiPostRegisterOptionalParams extends msRest.RequestOptionsBase {
  referralKey?: string;
}

/**
 * Optional Parameters.
 */
export interface SupportHubApiGetGitHubAuthTokenOptionalParams extends msRest.RequestOptionsBase {
  /**
   * Code received from GitHub
   */
  code?: string;
}

/**
 * Optional Parameters.
 */
export interface SupportHubApiGetGitLabAuthTokenOptionalParams extends msRest.RequestOptionsBase {
  /**
   * Access code received from GitLab
   */
  accessToken?: string;
}

/**
 * Optional Parameters.
 */
export interface SupportHubApiEditProjectOptionalParams extends msRest.RequestOptionsBase {
  /**
   * Project description
   */
  description?: string;
}

/**
 * Optional Parameters.
 */
export interface SupportHubApiCreateCardOptionalParams extends msRest.RequestOptionsBase {
  description?: string;
  columnOrder?: number;
}

/**
 * Optional Parameters.
 */
export interface SupportHubApiEditCardOptionalParams extends msRest.RequestOptionsBase {
  name?: string;
  description?: string;
  columnOrder?: number;
  columnGuid?: string;
}

/**
 * Defines values for ServiceType.
 * Possible values include: 'GitHub', 'GitLab'
 * @readonly
 * @enum {string}
 */
export type ServiceType = 'GitHub' | 'GitLab';

/**
 * Defines values for EntityType.
 * Possible values include: 'ProjectCategory', 'Project', 'Board', 'Card', 'BacklogItem',
 * 'UserBalance', 'User', 'ProjectProductPurchase', 'BoardColumn'
 * @readonly
 * @enum {string}
 */
export type EntityType = 'ProjectCategory' | 'Project' | 'Board' | 'Card' | 'BacklogItem' | 'UserBalance' | 'User' | 'ProjectProductPurchase' | 'BoardColumn';

/**
 * Defines values for CurrencyType.
 * Possible values include: 'Usd', 'BitCoin', 'Ethereum', 'Erc20Token', 'Waves', 'WavesToken',
 * 'LiteCoin'
 * @readonly
 * @enum {string}
 */
export type CurrencyType = 'Usd' | 'BitCoin' | 'Ethereum' | 'Erc20Token' | 'Waves' | 'WavesToken' | 'LiteCoin';

/**
 * Defines values for CurrencyType1.
 * Possible values include: 'Usd', 'BitCoin', 'Ethereum', 'Erc20Token', 'Waves', 'WavesToken',
 * 'LiteCoin'
 * @readonly
 * @enum {string}
 */
export type CurrencyType1 = 'Usd' | 'BitCoin' | 'Ethereum' | 'Erc20Token' | 'Waves' | 'WavesToken' | 'LiteCoin';

/**
 * Defines values for EntityType1.
 * Possible values include: 'ProjectCategory', 'Project', 'Board', 'Card', 'BacklogItem',
 * 'UserBalance', 'User', 'ProjectProductPurchase', 'BoardColumn'
 * @readonly
 * @enum {string}
 */
export type EntityType1 = 'ProjectCategory' | 'Project' | 'Board' | 'Card' | 'BacklogItem' | 'UserBalance' | 'User' | 'ProjectProductPurchase' | 'BoardColumn';

/**
 * Defines values for CurrencyType2.
 * Possible values include: 'Usd', 'BitCoin', 'Ethereum', 'Erc20Token', 'Waves', 'WavesToken',
 * 'LiteCoin'
 * @readonly
 * @enum {string}
 */
export type CurrencyType2 = 'Usd' | 'BitCoin' | 'Ethereum' | 'Erc20Token' | 'Waves' | 'WavesToken' | 'LiteCoin';

/**
 * Defines values for CurrencyType3.
 * Possible values include: 'Usd', 'BitCoin', 'Ethereum', 'Erc20Token', 'Waves', 'WavesToken',
 * 'LiteCoin'
 * @readonly
 * @enum {string}
 */
export type CurrencyType3 = 'Usd' | 'BitCoin' | 'Ethereum' | 'Erc20Token' | 'Waves' | 'WavesToken' | 'LiteCoin';

/**
 * Defines values for ServiceType1.
 * Possible values include: 'GitHub', 'GitLab'
 * @readonly
 * @enum {string}
 */
export type ServiceType1 = 'GitHub' | 'GitLab';

/**
 * Defines values for EntityType2.
 * Possible values include: 'ProjectCategory', 'Project', 'Board', 'Card', 'BacklogItem',
 * 'UserBalance', 'User', 'ProjectProductPurchase', 'BoardColumn'
 * @readonly
 * @enum {string}
 */
export type EntityType2 = 'ProjectCategory' | 'Project' | 'Board' | 'Card' | 'BacklogItem' | 'UserBalance' | 'User' | 'ProjectProductPurchase' | 'BoardColumn';

/**
 * Defines values for EntityType3.
 * Possible values include: 'ProjectCategory', 'Project', 'Board', 'Card', 'BacklogItem',
 * 'UserBalance', 'User', 'ProjectProductPurchase', 'BoardColumn'
 * @readonly
 * @enum {string}
 */
export type EntityType3 = 'ProjectCategory' | 'Project' | 'Board' | 'Card' | 'BacklogItem' | 'UserBalance' | 'User' | 'ProjectProductPurchase' | 'BoardColumn';

/**
 * Defines values for CurrencyType4.
 * Possible values include: 'Usd', 'BitCoin', 'Ethereum', 'Erc20Token', 'Waves', 'WavesToken',
 * 'LiteCoin'
 * @readonly
 * @enum {string}
 */
export type CurrencyType4 = 'Usd' | 'BitCoin' | 'Ethereum' | 'Erc20Token' | 'Waves' | 'WavesToken' | 'LiteCoin';

/**
 * Defines values for EntityType4.
 * Possible values include: 'ProjectCategory', 'Project', 'Board', 'Card', 'BacklogItem',
 * 'UserBalance', 'User', 'ProjectProductPurchase', 'BoardColumn'
 * @readonly
 * @enum {string}
 */
export type EntityType4 = 'ProjectCategory' | 'Project' | 'Board' | 'Card' | 'BacklogItem' | 'UserBalance' | 'User' | 'ProjectProductPurchase' | 'BoardColumn';

/**
 * Contains response data for the getLogin operation.
 */
export type GetLoginResponse = GetLoginOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GetLoginOKResponse;
    };
};

/**
 * Contains response data for the postRegister operation.
 */
export type PostRegisterResponse = PostRegisterOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: PostRegisterOKResponse;
    };
};

/**
 * Contains response data for the postConfirmEmail operation.
 */
export type PostConfirmEmailResponse = PostConfirmEmailOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: PostConfirmEmailOKResponse;
    };
};

/**
 * Contains response data for the getGitHubLoginLink operation.
 */
export type GetGitHubLoginLinkResponse = GetGitHubLoginLinkOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GetGitHubLoginLinkOKResponse;
    };
};

/**
 * Contains response data for the getGitHubAuthToken operation.
 */
export type GetGitHubAuthTokenResponse = GetGitHubAuthTokenOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GetGitHubAuthTokenOKResponse;
    };
};

/**
 * Contains response data for the getGitLabLoginLink operation.
 */
export type GetGitLabLoginLinkResponse = GetGitLabLoginLinkOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GetGitLabLoginLinkOKResponse;
    };
};

/**
 * Contains response data for the getGitLabAuthToken operation.
 */
export type GetGitLabAuthTokenResponse = GetGitLabAuthTokenOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GetGitLabAuthTokenOKResponse;
    };
};

/**
 * Contains response data for the getMeExternalRepositories operation.
 */
export type GetMeExternalRepositoriesResponse = GetMeExternalRepositoriesOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GetMeExternalRepositoriesOKResponse;
    };
};

/**
 * Contains response data for the getMyIntegrationsStatus operation.
 */
export type GetMyIntegrationsStatusResponse = GetMyIntegrationsStatusOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GetMyIntegrationsStatusOKResponse;
    };
};

/**
 * Contains response data for the postImportRepository operation.
 */
export type PostImportRepositoryResponse = PostImportRepositoryOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: PostImportRepositoryOKResponse;
    };
};

/**
 * Contains response data for the getRepo operation.
 */
export type GetRepoResponse = GetRepoOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GetRepoOKResponse;
    };
};

/**
 * Contains response data for the getProject operation.
 */
export type GetProjectResponse = GetProjectOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GetProjectOKResponse;
    };
};

/**
 * Contains response data for the editProject operation.
 */
export type EditProjectResponse = EditProjectOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: EditProjectOKResponse;
    };
};

/**
 * Contains response data for the getProjectBoards operation.
 */
export type GetProjectBoardsResponse = GetProjectBoardsOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GetProjectBoardsOKResponse;
    };
};

/**
 * Contains response data for the getBoard operation.
 */
export type GetBoardResponse = GetBoardOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GetBoardOKResponse;
    };
};

/**
 * Contains response data for the getBoardColumns operation.
 */
export type GetBoardColumnsResponse = GetBoardColumnsOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GetBoardColumnsOKResponse;
    };
};

/**
 * Contains response data for the getColumnCards operation.
 */
export type GetColumnCardsResponse = GetColumnCardsOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GetColumnCardsOKResponse;
    };
};

/**
 * Contains response data for the getProjectByAlias operation.
 */
export type GetProjectByAliasResponse = GetProjectByAliasOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GetProjectByAliasOKResponse;
    };
};

/**
 * Contains response data for the createCard operation.
 */
export type CreateCardResponse = CreateCardCreatedResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: CreateCardCreatedResponse;
    };
};

/**
 * Contains response data for the editCard operation.
 */
export type EditCardResponse = EditCardOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: EditCardOKResponse;
    };
};

/**
 * Contains response data for the getCardWork operation.
 */
export type GetCardWorkResponse = GetCardWorkOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GetCardWorkOKResponse;
    };
};

/**
 * Contains response data for the getEntityFundingBalances operation.
 */
export type GetEntityFundingBalancesResponse = GetEntityFundingBalancesOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GetEntityFundingBalancesOKResponse;
    };
};

/**
 * Contains response data for the getCardProject operation.
 */
export type GetCardProjectResponse = GetCardProjectOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GetCardProjectOKResponse;
    };
};

/**
 * Contains response data for the getProjectWorkTypes operation.
 */
export type GetProjectWorkTypesResponse = GetProjectWorkTypesOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GetProjectWorkTypesOKResponse;
    };
};

/**
 * Contains response data for the postSubmitCardWork operation.
 */
export type PostSubmitCardWorkResponse = PostSubmitCardWorkOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: PostSubmitCardWorkOKResponse;
    };
};

/**
 * Contains response data for the postInvoice operation.
 */
export type PostInvoiceResponse = PostInvoiceCreatedResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: PostInvoiceCreatedResponse;
    };
};

/**
 * Contains response data for the getMyInvoice operation.
 */
export type GetMyInvoiceResponse = GetMyInvoiceOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GetMyInvoiceOKResponse;
    };
};

/**
 * Contains response data for the getMyActiveInvoices operation.
 */
export type GetMyActiveInvoicesResponse = GetMyActiveInvoicesOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GetMyActiveInvoicesOKResponse;
    };
};

/**
 * Contains response data for the getMyFinishedInvoices operation.
 */
export type GetMyFinishedInvoicesResponse = GetMyFinishedInvoicesOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GetMyFinishedInvoicesOKResponse;
    };
};

/**
 * Contains response data for the patchMyInvoice operation.
 */
export type PatchMyInvoiceResponse = PatchMyInvoiceOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: PatchMyInvoiceOKResponse;
    };
};

/**
 * Contains response data for the getMyBalances operation.
 */
export type GetMyBalancesResponse = GetMyBalancesOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GetMyBalancesOKResponse;
    };
};

/**
 * Contains response data for the getMySetting operation.
 */
export type GetMySettingResponse = GetMySettingOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GetMySettingOKResponse;
    };
};

/**
 * Contains response data for the setMySetting operation.
 */
export type SetMySettingResponse = SetMySettingOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: SetMySettingOKResponse;
    };
};

/**
 * Contains response data for the getMyLibraryProjects operation.
 */
export type GetMyLibraryProjectsResponse = GetMyLibraryProjectsOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GetMyLibraryProjectsOKResponse;
    };
};

/**
 * Contains response data for the addProjectToMyLibrary operation.
 */
export type AddProjectToMyLibraryResponse = AddProjectToMyLibraryCreatedResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: AddProjectToMyLibraryCreatedResponse;
    };
};

/**
 * Contains response data for the removeProjectFromMyLibrary operation.
 */
export type RemoveProjectFromMyLibraryResponse = RemoveProjectFromMyLibraryOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: RemoveProjectFromMyLibraryOKResponse;
    };
};

/**
 * Contains response data for the getMyLibraryProjectStatus operation.
 */
export type GetMyLibraryProjectStatusResponse = GetMyLibraryProjectStatusOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GetMyLibraryProjectStatusOKResponse;
    };
};

/**
 * Contains response data for the getMe operation.
 */
export type GetMeResponse = GetMeOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GetMeOKResponse;
    };
};

/**
 * Contains response data for the getUser operation.
 */
export type GetUserResponse = GetUserOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GetUserOKResponse;
    };
};

/**
 * Contains response data for the loginViaFacebook operation.
 */
export type LoginViaFacebookResponse = LoginViaFacebookOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: LoginViaFacebookOKResponse;
    };
};

/**
 * Contains response data for the loginViaGoogle operation.
 */
export type LoginViaGoogleResponse = LoginViaGoogleOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: LoginViaGoogleOKResponse;
    };
};

/**
 * Contains response data for the getMyEntityPermissions operation.
 */
export type GetMyEntityPermissionsResponse = GetMyEntityPermissionsOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GetMyEntityPermissionsOKResponse;
    };
};

/**
 * Contains response data for the getNewestProjects operation.
 */
export type GetNewestProjectsResponse = GetNewestProjectsOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GetNewestProjectsOKResponse;
    };
};

/**
 * Contains response data for the getRandomProjects operation.
 */
export type GetRandomProjectsResponse = GetRandomProjectsOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GetRandomProjectsOKResponse;
    };
};

/**
 * Contains response data for the getProjectProducts operation.
 */
export type GetProjectProductsResponse = GetProjectProductsOKResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GetProjectProductsOKResponse;
    };
};
