/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as msRest from "@azure/ms-rest-js";


export const User: msRest.CompositeMapper = {
  serializedName: "User",
  type: {
    name: "Composite",
    className: "User",
    modelProperties: {
      guid: {
        serializedName: "guid",
        type: {
          name: "String"
        }
      },
      login: {
        serializedName: "login",
        type: {
          name: "String"
        }
      },
      email: {
        serializedName: "email",
        type: {
          name: "String"
        }
      },
      registerDate: {
        serializedName: "register_date",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ExternalRepoOwner: msRest.CompositeMapper = {
  serializedName: "ExternalRepo_owner",
  type: {
    name: "Composite",
    className: "ExternalRepoOwner",
    modelProperties: {
      login: {
        serializedName: "login",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ExternalRepo: msRest.CompositeMapper = {
  serializedName: "ExternalRepo",
  type: {
    name: "Composite",
    className: "ExternalRepo",
    modelProperties: {
      originId: {
        serializedName: "origin_id",
        type: {
          name: "String"
        }
      },
      fullName: {
        serializedName: "full_name",
        type: {
          name: "String"
        }
      },
      description: {
        serializedName: "description",
        type: {
          name: "String"
        }
      },
      serviceType: {
        serializedName: "service_type",
        type: {
          name: "String"
        }
      },
      owner: {
        serializedName: "owner",
        type: {
          name: "Composite",
          className: "ExternalRepoOwner"
        }
      }
    }
  }
};

export const Project: msRest.CompositeMapper = {
  serializedName: "Project",
  type: {
    name: "Composite",
    className: "Project",
    modelProperties: {
      guid: {
        serializedName: "guid",
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      description: {
        serializedName: "description",
        type: {
          name: "String"
        }
      },
      repositoryGuid: {
        serializedName: "repository_guid",
        type: {
          name: "String"
        }
      },
      creatorGuid: {
        serializedName: "creator_guid",
        type: {
          name: "String"
        }
      },
      baseUri: {
        serializedName: "base_uri",
        type: {
          name: "String"
        }
      },
      starsCount: {
        serializedName: "stars_count",
        type: {
          name: "Number"
        }
      },
      createdAt: {
        serializedName: "created_at",
        type: {
          name: "String"
        }
      },
      updatedAt: {
        serializedName: "updated_at",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const Repository: msRest.CompositeMapper = {
  serializedName: "Repository",
  type: {
    name: "Composite",
    className: "Repository",
    modelProperties: {
      guid: {
        serializedName: "guid",
        type: {
          name: "String"
        }
      },
      creator: {
        serializedName: "creator",
        type: {
          name: "Composite",
          className: "User"
        }
      },
      title: {
        serializedName: "title",
        type: {
          name: "String"
        }
      },
      repoUrl: {
        serializedName: "repo_url",
        type: {
          name: "String"
        }
      },
      originId: {
        serializedName: "origin_id",
        type: {
          name: "String"
        }
      },
      createdAt: {
        serializedName: "created_at",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const Board: msRest.CompositeMapper = {
  serializedName: "Board",
  type: {
    name: "Composite",
    className: "Board",
    modelProperties: {
      guid: {
        serializedName: "guid",
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      description: {
        serializedName: "description",
        type: {
          name: "String"
        }
      },
      projectGuid: {
        serializedName: "project_guid",
        type: {
          name: "String"
        }
      },
      userGuid: {
        serializedName: "user_guid",
        type: {
          name: "String"
        }
      },
      createdAt: {
        serializedName: "created_at",
        type: {
          name: "String"
        }
      },
      updatedAt: {
        serializedName: "updated_at",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const Column: msRest.CompositeMapper = {
  serializedName: "Column",
  type: {
    name: "Composite",
    className: "Column",
    modelProperties: {
      guid: {
        serializedName: "guid",
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      boardGuid: {
        serializedName: "board_guid",
        type: {
          name: "String"
        }
      },
      boardOrder: {
        serializedName: "board_order",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const Card: msRest.CompositeMapper = {
  serializedName: "Card",
  type: {
    name: "Composite",
    className: "Card",
    modelProperties: {
      guid: {
        serializedName: "guid",
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      description: {
        serializedName: "description",
        type: {
          name: "String"
        }
      },
      creatorGuid: {
        serializedName: "creator_guid",
        type: {
          name: "String"
        }
      },
      columnOrder: {
        serializedName: "column_order",
        type: {
          name: "Number"
        }
      },
      columnGuid: {
        serializedName: "column_guid",
        type: {
          name: "String"
        }
      },
      createdAt: {
        serializedName: "created_at",
        type: {
          name: "String"
        }
      },
      updatedAt: {
        serializedName: "updated_at",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ProjectWorkType: msRest.CompositeMapper = {
  serializedName: "ProjectWorkType",
  type: {
    name: "Composite",
    className: "ProjectWorkType",
    modelProperties: {
      guid: {
        serializedName: "guid",
        type: {
          name: "String"
        }
      },
      projectGuid: {
        serializedName: "project_guid",
        type: {
          name: "String"
        }
      },
      title: {
        serializedName: "title",
        type: {
          name: "String"
        }
      },
      budgetPercent: {
        serializedName: "budget_percent",
        type: {
          name: "Number"
        }
      },
      createdAt: {
        serializedName: "created_at",
        type: {
          name: "String"
        }
      },
      updatedAt: {
        serializedName: "updated_at",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const CardWork: msRest.CompositeMapper = {
  serializedName: "CardWork",
  type: {
    name: "Composite",
    className: "CardWork",
    modelProperties: {
      guid: {
        serializedName: "guid",
        type: {
          name: "String"
        }
      },
      userGuid: {
        serializedName: "user_guid",
        type: {
          name: "String"
        }
      },
      cardGuid: {
        serializedName: "card_guid",
        type: {
          name: "String"
        }
      },
      workType: {
        serializedName: "work_type",
        type: {
          name: "Composite",
          className: "ProjectWorkType"
        }
      },
      proof: {
        serializedName: "proof",
        type: {
          name: "String"
        }
      },
      createdAt: {
        serializedName: "created_at",
        type: {
          name: "String"
        }
      },
      updatedAt: {
        serializedName: "updated_at",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const FundingBalance: msRest.CompositeMapper = {
  serializedName: "FundingBalance",
  type: {
    name: "Composite",
    className: "FundingBalance",
    modelProperties: {
      guid: {
        serializedName: "guid",
        type: {
          name: "String"
        }
      },
      entityGuid: {
        serializedName: "entity_guid",
        type: {
          name: "String"
        }
      },
      entityType: {
        serializedName: "entity_type",
        type: {
          name: "String"
        }
      },
      amount: {
        serializedName: "amount",
        type: {
          name: "Number"
        }
      },
      currencyType: {
        serializedName: "currency_type",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const CurrencyWallet: msRest.CompositeMapper = {
  serializedName: "CurrencyWallet",
  type: {
    name: "Composite",
    className: "CurrencyWallet",
    modelProperties: {
      guid: {
        serializedName: "guid",
        type: {
          name: "String"
        }
      },
      address: {
        serializedName: "address",
        type: {
          name: "String"
        }
      },
      currencyType: {
        serializedName: "currency_type",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const Invoice: msRest.CompositeMapper = {
  serializedName: "Invoice",
  type: {
    name: "Composite",
    className: "Invoice",
    modelProperties: {
      guid: {
        serializedName: "guid",
        type: {
          name: "String"
        }
      },
      userId: {
        serializedName: "user_id",
        type: {
          name: "String"
        }
      },
      entityGuid: {
        serializedName: "entity_guid",
        type: {
          name: "String"
        }
      },
      entityType: {
        serializedName: "entity_type",
        type: {
          name: "String"
        }
      },
      amount: {
        serializedName: "amount",
        type: {
          name: "Number"
        }
      },
      currencyType: {
        serializedName: "currency_type",
        type: {
          name: "String"
        }
      },
      wallet: {
        serializedName: "wallet",
        type: {
          name: "Composite",
          className: "CurrencyWallet"
        }
      },
      createdAt: {
        serializedName: "created_at",
        type: {
          name: "String"
        }
      },
      updatedAt: {
        serializedName: "updated_at",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const UserBalance: msRest.CompositeMapper = {
  serializedName: "UserBalance",
  type: {
    name: "Composite",
    className: "UserBalance",
    modelProperties: {
      guid: {
        serializedName: "guid",
        type: {
          name: "String"
        }
      },
      userGuid: {
        serializedName: "user_guid",
        type: {
          name: "String"
        }
      },
      currencyType: {
        serializedName: "currency_type",
        type: {
          name: "String"
        }
      },
      amount: {
        serializedName: "amount",
        type: {
          name: "Number"
        }
      },
      createdAt: {
        serializedName: "created_at",
        type: {
          name: "String"
        }
      },
      updatedAt: {
        serializedName: "updated_at",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const UserSetting: msRest.CompositeMapper = {
  serializedName: "UserSetting",
  type: {
    name: "Composite",
    className: "UserSetting",
    modelProperties: {
      guid: {
        serializedName: "guid",
        type: {
          name: "String"
        }
      },
      userGuid: {
        serializedName: "user_guid",
        type: {
          name: "String"
        }
      },
      key: {
        serializedName: "key",
        type: {
          name: "String"
        }
      },
      value: {
        serializedName: "value",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const LibraryItem: msRest.CompositeMapper = {
  serializedName: "LibraryItem",
  type: {
    name: "Composite",
    className: "LibraryItem",
    modelProperties: {
      guid: {
        serializedName: "guid",
        type: {
          name: "String"
        }
      },
      userGuid: {
        serializedName: "user_guid",
        type: {
          name: "String"
        }
      },
      projectGuid: {
        serializedName: "project_guid",
        type: {
          name: "String"
        }
      },
      createdAt: {
        serializedName: "created_at",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ProjectProduct: msRest.CompositeMapper = {
  serializedName: "ProjectProduct",
  type: {
    name: "Composite",
    className: "ProjectProduct",
    modelProperties: {
      guid: {
        serializedName: "guid",
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      description: {
        serializedName: "description",
        type: {
          name: "String"
        }
      },
      url: {
        serializedName: "url",
        type: {
          name: "String"
        }
      },
      projectGuid: {
        serializedName: "project_guid",
        type: {
          name: "String"
        }
      },
      usdPrice: {
        serializedName: "usd_price",
        type: {
          name: "Number"
        }
      },
      durationHours: {
        serializedName: "duration_hours",
        type: {
          name: "Number"
        }
      },
      createdAt: {
        serializedName: "created_at",
        type: {
          name: "String"
        }
      },
      updatedAt: {
        serializedName: "updated_at",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const GetLoginOKResponseData: msRest.CompositeMapper = {
  serializedName: "GetLoginOKResponse_data",
  type: {
    name: "Composite",
    className: "GetLoginOKResponseData",
    modelProperties: {
      token: {
        serializedName: "token",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const GetLoginOKResponse: msRest.CompositeMapper = {
  serializedName: "GetLoginOKResponse",
  type: {
    name: "Composite",
    className: "GetLoginOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "GetLoginOKResponseData"
        }
      }
    }
  }
};

export const PostRegisterOKResponseData: msRest.CompositeMapper = {
  serializedName: "PostRegisterOKResponse_data",
  type: {
    name: "Composite",
    className: "PostRegisterOKResponseData",
    modelProperties: {
      response: {
        serializedName: "response",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const PostRegisterOKResponse: msRest.CompositeMapper = {
  serializedName: "PostRegisterOKResponse",
  type: {
    name: "Composite",
    className: "PostRegisterOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "PostRegisterOKResponseData"
        }
      }
    }
  }
};

export const PostConfirmEmailOKResponseData: msRest.CompositeMapper = {
  serializedName: "PostConfirmEmailOKResponse_data",
  type: {
    name: "Composite",
    className: "PostConfirmEmailOKResponseData",
    modelProperties: {
      token: {
        serializedName: "token",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const PostConfirmEmailOKResponse: msRest.CompositeMapper = {
  serializedName: "PostConfirmEmailOKResponse",
  type: {
    name: "Composite",
    className: "PostConfirmEmailOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "PostConfirmEmailOKResponseData"
        }
      }
    }
  }
};

export const GetGitHubLoginLinkOKResponseData: msRest.CompositeMapper = {
  serializedName: "GetGitHubLoginLinkOKResponse_data",
  type: {
    name: "Composite",
    className: "GetGitHubLoginLinkOKResponseData",
    modelProperties: {
      loginLink: {
        serializedName: "login_link",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const GetGitHubLoginLinkOKResponse: msRest.CompositeMapper = {
  serializedName: "GetGitHubLoginLinkOKResponse",
  type: {
    name: "Composite",
    className: "GetGitHubLoginLinkOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "GetGitHubLoginLinkOKResponseData"
        }
      }
    }
  }
};

export const GetGitHubAuthTokenOKResponseData: msRest.CompositeMapper = {
  serializedName: "GetGitHubAuthTokenOKResponse_data",
  type: {
    name: "Composite",
    className: "GetGitHubAuthTokenOKResponseData",
    modelProperties: {
      token: {
        serializedName: "token",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const GetGitHubAuthTokenOKResponse: msRest.CompositeMapper = {
  serializedName: "GetGitHubAuthTokenOKResponse",
  type: {
    name: "Composite",
    className: "GetGitHubAuthTokenOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "GetGitHubAuthTokenOKResponseData"
        }
      }
    }
  }
};

export const GetGitLabLoginLinkOKResponseData: msRest.CompositeMapper = {
  serializedName: "GetGitLabLoginLinkOKResponse_data",
  type: {
    name: "Composite",
    className: "GetGitLabLoginLinkOKResponseData",
    modelProperties: {
      loginLink: {
        serializedName: "login_link",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const GetGitLabLoginLinkOKResponse: msRest.CompositeMapper = {
  serializedName: "GetGitLabLoginLinkOKResponse",
  type: {
    name: "Composite",
    className: "GetGitLabLoginLinkOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "GetGitLabLoginLinkOKResponseData"
        }
      }
    }
  }
};

export const GetGitLabAuthTokenOKResponseData: msRest.CompositeMapper = {
  serializedName: "GetGitLabAuthTokenOKResponse_data",
  type: {
    name: "Composite",
    className: "GetGitLabAuthTokenOKResponseData",
    modelProperties: {
      token: {
        serializedName: "token",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const GetGitLabAuthTokenOKResponse: msRest.CompositeMapper = {
  serializedName: "GetGitLabAuthTokenOKResponse",
  type: {
    name: "Composite",
    className: "GetGitLabAuthTokenOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "GetGitLabAuthTokenOKResponseData"
        }
      }
    }
  }
};

export const GetMeExternalRepositoriesOKResponseData: msRest.CompositeMapper = {
  serializedName: "GetMeExternalRepositoriesOKResponse_data",
  type: {
    name: "Composite",
    className: "GetMeExternalRepositoriesOKResponseData",
    modelProperties: {
      repositories: {
        serializedName: "repositories",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "ExternalRepo"
            }
          }
        }
      }
    }
  }
};

export const GetMeExternalRepositoriesOKResponse: msRest.CompositeMapper = {
  serializedName: "GetMeExternalRepositoriesOKResponse",
  type: {
    name: "Composite",
    className: "GetMeExternalRepositoriesOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "GetMeExternalRepositoriesOKResponseData"
        }
      }
    }
  }
};

export const GetMyIntegrationsStatusOKResponseDataIntegrationsGithubUser: msRest.CompositeMapper = {
  serializedName: "GetMyIntegrationsStatusOKResponse_data_integrations_github_user",
  type: {
    name: "Composite",
    className: "GetMyIntegrationsStatusOKResponseDataIntegrationsGithubUser",
    modelProperties: {
      email: {
        serializedName: "email",
        type: {
          name: "String"
        }
      },
      login: {
        serializedName: "login",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const GetMyIntegrationsStatusOKResponseDataIntegrationsGithub: msRest.CompositeMapper = {
  serializedName: "GetMyIntegrationsStatusOKResponse_data_integrations_github",
  type: {
    name: "Composite",
    className: "GetMyIntegrationsStatusOKResponseDataIntegrationsGithub",
    modelProperties: {
      connected: {
        serializedName: "connected",
        type: {
          name: "Boolean"
        }
      },
      user: {
        serializedName: "user",
        type: {
          name: "Composite",
          className: "GetMyIntegrationsStatusOKResponseDataIntegrationsGithubUser"
        }
      }
    }
  }
};

export const GetMyIntegrationsStatusOKResponseDataIntegrationsGitlabUser: msRest.CompositeMapper = {
  serializedName: "GetMyIntegrationsStatusOKResponse_data_integrations_gitlab_user",
  type: {
    name: "Composite",
    className: "GetMyIntegrationsStatusOKResponseDataIntegrationsGitlabUser",
    modelProperties: {
      email: {
        serializedName: "email",
        type: {
          name: "String"
        }
      },
      login: {
        serializedName: "login",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const GetMyIntegrationsStatusOKResponseDataIntegrationsGitlab: msRest.CompositeMapper = {
  serializedName: "GetMyIntegrationsStatusOKResponse_data_integrations_gitlab",
  type: {
    name: "Composite",
    className: "GetMyIntegrationsStatusOKResponseDataIntegrationsGitlab",
    modelProperties: {
      connected: {
        serializedName: "connected",
        type: {
          name: "Boolean"
        }
      },
      user: {
        serializedName: "user",
        type: {
          name: "Composite",
          className: "GetMyIntegrationsStatusOKResponseDataIntegrationsGitlabUser"
        }
      }
    }
  }
};

export const GetMyIntegrationsStatusOKResponseDataIntegrations: msRest.CompositeMapper = {
  serializedName: "GetMyIntegrationsStatusOKResponse_data_integrations",
  type: {
    name: "Composite",
    className: "GetMyIntegrationsStatusOKResponseDataIntegrations",
    modelProperties: {
      github: {
        serializedName: "github",
        type: {
          name: "Composite",
          className: "GetMyIntegrationsStatusOKResponseDataIntegrationsGithub"
        }
      },
      gitlab: {
        serializedName: "gitlab",
        type: {
          name: "Composite",
          className: "GetMyIntegrationsStatusOKResponseDataIntegrationsGitlab"
        }
      }
    }
  }
};

export const GetMyIntegrationsStatusOKResponseData: msRest.CompositeMapper = {
  serializedName: "GetMyIntegrationsStatusOKResponse_data",
  type: {
    name: "Composite",
    className: "GetMyIntegrationsStatusOKResponseData",
    modelProperties: {
      integrations: {
        serializedName: "integrations",
        type: {
          name: "Composite",
          className: "GetMyIntegrationsStatusOKResponseDataIntegrations"
        }
      }
    }
  }
};

export const GetMyIntegrationsStatusOKResponse: msRest.CompositeMapper = {
  serializedName: "GetMyIntegrationsStatusOKResponse",
  type: {
    name: "Composite",
    className: "GetMyIntegrationsStatusOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "GetMyIntegrationsStatusOKResponseData"
        }
      }
    }
  }
};

export const PostImportRepositoryOKResponseData: msRest.CompositeMapper = {
  serializedName: "PostImportRepositoryOKResponse_data",
  type: {
    name: "Composite",
    className: "PostImportRepositoryOKResponseData",
    modelProperties: {
      project: {
        serializedName: "project",
        type: {
          name: "Composite",
          className: "Project"
        }
      },
      repository: {
        serializedName: "repository",
        type: {
          name: "Composite",
          className: "Repository"
        }
      }
    }
  }
};

export const PostImportRepositoryOKResponse: msRest.CompositeMapper = {
  serializedName: "PostImportRepositoryOKResponse",
  type: {
    name: "Composite",
    className: "PostImportRepositoryOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "PostImportRepositoryOKResponseData"
        }
      }
    }
  }
};

export const GetRepoOKResponseData: msRest.CompositeMapper = {
  serializedName: "GetRepoOKResponse_data",
  type: {
    name: "Composite",
    className: "GetRepoOKResponseData",
    modelProperties: {
      repository: {
        serializedName: "repository",
        type: {
          name: "Composite",
          className: "Repository"
        }
      }
    }
  }
};

export const GetRepoOKResponse: msRest.CompositeMapper = {
  serializedName: "GetRepoOKResponse",
  type: {
    name: "Composite",
    className: "GetRepoOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "GetRepoOKResponseData"
        }
      }
    }
  }
};

export const GetProjectOKResponseData: msRest.CompositeMapper = {
  serializedName: "GetProjectOKResponse_data",
  type: {
    name: "Composite",
    className: "GetProjectOKResponseData",
    modelProperties: {
      project: {
        serializedName: "project",
        type: {
          name: "Composite",
          className: "Project"
        }
      }
    }
  }
};

export const GetProjectOKResponse: msRest.CompositeMapper = {
  serializedName: "GetProjectOKResponse",
  type: {
    name: "Composite",
    className: "GetProjectOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "GetProjectOKResponseData"
        }
      }
    }
  }
};

export const EditProjectOKResponseData: msRest.CompositeMapper = {
  serializedName: "EditProjectOKResponse_data",
  type: {
    name: "Composite",
    className: "EditProjectOKResponseData",
    modelProperties: {
      project: {
        serializedName: "project",
        type: {
          name: "Composite",
          className: "Project"
        }
      }
    }
  }
};

export const EditProjectOKResponse: msRest.CompositeMapper = {
  serializedName: "EditProjectOKResponse",
  type: {
    name: "Composite",
    className: "EditProjectOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "EditProjectOKResponseData"
        }
      }
    }
  }
};

export const GetProjectBoardsOKResponseData: msRest.CompositeMapper = {
  serializedName: "GetProjectBoardsOKResponse_data",
  type: {
    name: "Composite",
    className: "GetProjectBoardsOKResponseData",
    modelProperties: {
      boards: {
        serializedName: "boards",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Board"
            }
          }
        }
      }
    }
  }
};

export const GetProjectBoardsOKResponse: msRest.CompositeMapper = {
  serializedName: "GetProjectBoardsOKResponse",
  type: {
    name: "Composite",
    className: "GetProjectBoardsOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "GetProjectBoardsOKResponseData"
        }
      }
    }
  }
};

export const GetBoardOKResponseData: msRest.CompositeMapper = {
  serializedName: "GetBoardOKResponse_data",
  type: {
    name: "Composite",
    className: "GetBoardOKResponseData",
    modelProperties: {
      board: {
        serializedName: "board",
        type: {
          name: "Composite",
          className: "Board"
        }
      }
    }
  }
};

export const GetBoardOKResponse: msRest.CompositeMapper = {
  serializedName: "GetBoardOKResponse",
  type: {
    name: "Composite",
    className: "GetBoardOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "GetBoardOKResponseData"
        }
      }
    }
  }
};

export const GetBoardColumnsOKResponseData: msRest.CompositeMapper = {
  serializedName: "GetBoardColumnsOKResponse_data",
  type: {
    name: "Composite",
    className: "GetBoardColumnsOKResponseData",
    modelProperties: {
      columns: {
        serializedName: "columns",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Column"
            }
          }
        }
      }
    }
  }
};

export const GetBoardColumnsOKResponse: msRest.CompositeMapper = {
  serializedName: "GetBoardColumnsOKResponse",
  type: {
    name: "Composite",
    className: "GetBoardColumnsOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "GetBoardColumnsOKResponseData"
        }
      }
    }
  }
};

export const GetColumnCardsOKResponseData: msRest.CompositeMapper = {
  serializedName: "GetColumnCardsOKResponse_data",
  type: {
    name: "Composite",
    className: "GetColumnCardsOKResponseData",
    modelProperties: {
      cards: {
        serializedName: "cards",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Card"
            }
          }
        }
      }
    }
  }
};

export const GetColumnCardsOKResponse: msRest.CompositeMapper = {
  serializedName: "GetColumnCardsOKResponse",
  type: {
    name: "Composite",
    className: "GetColumnCardsOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "GetColumnCardsOKResponseData"
        }
      }
    }
  }
};

export const GetProjectByAliasOKResponseData: msRest.CompositeMapper = {
  serializedName: "GetProjectByAliasOKResponse_data",
  type: {
    name: "Composite",
    className: "GetProjectByAliasOKResponseData",
    modelProperties: {
      project: {
        serializedName: "project",
        type: {
          name: "Composite",
          className: "Project"
        }
      }
    }
  }
};

export const GetProjectByAliasOKResponse: msRest.CompositeMapper = {
  serializedName: "GetProjectByAliasOKResponse",
  type: {
    name: "Composite",
    className: "GetProjectByAliasOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "GetProjectByAliasOKResponseData"
        }
      }
    }
  }
};

export const CreateCardCreatedResponseData: msRest.CompositeMapper = {
  serializedName: "CreateCardCreatedResponse_data",
  type: {
    name: "Composite",
    className: "CreateCardCreatedResponseData",
    modelProperties: {
      card: {
        serializedName: "card",
        type: {
          name: "Composite",
          className: "Card"
        }
      }
    }
  }
};

export const CreateCardCreatedResponse: msRest.CompositeMapper = {
  serializedName: "CreateCardCreatedResponse",
  type: {
    name: "Composite",
    className: "CreateCardCreatedResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "CreateCardCreatedResponseData"
        }
      }
    }
  }
};

export const EditCardOKResponseData: msRest.CompositeMapper = {
  serializedName: "EditCardOKResponse_data",
  type: {
    name: "Composite",
    className: "EditCardOKResponseData",
    modelProperties: {
      card: {
        serializedName: "card",
        type: {
          name: "Composite",
          className: "Card"
        }
      }
    }
  }
};

export const EditCardOKResponse: msRest.CompositeMapper = {
  serializedName: "EditCardOKResponse",
  type: {
    name: "Composite",
    className: "EditCardOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "EditCardOKResponseData"
        }
      }
    }
  }
};

export const GetCardWorkOKResponseData: msRest.CompositeMapper = {
  serializedName: "GetCardWorkOKResponse_data",
  type: {
    name: "Composite",
    className: "GetCardWorkOKResponseData",
    modelProperties: {
      project: {
        serializedName: "project",
        type: {
          name: "Composite",
          className: "CardWork"
        }
      }
    }
  }
};

export const GetCardWorkOKResponse: msRest.CompositeMapper = {
  serializedName: "GetCardWorkOKResponse",
  type: {
    name: "Composite",
    className: "GetCardWorkOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "GetCardWorkOKResponseData"
        }
      }
    }
  }
};

export const GetEntityFundingBalancesOKResponseData: msRest.CompositeMapper = {
  serializedName: "GetEntityFundingBalancesOKResponse_data",
  type: {
    name: "Composite",
    className: "GetEntityFundingBalancesOKResponseData",
    modelProperties: {
      balances: {
        serializedName: "balances",
        type: {
          name: "Composite",
          className: "FundingBalance"
        }
      }
    }
  }
};

export const GetEntityFundingBalancesOKResponse: msRest.CompositeMapper = {
  serializedName: "GetEntityFundingBalancesOKResponse",
  type: {
    name: "Composite",
    className: "GetEntityFundingBalancesOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "GetEntityFundingBalancesOKResponseData"
        }
      }
    }
  }
};

export const GetCardProjectOKResponseData: msRest.CompositeMapper = {
  serializedName: "GetCardProjectOKResponse_data",
  type: {
    name: "Composite",
    className: "GetCardProjectOKResponseData",
    modelProperties: {
      project: {
        serializedName: "project",
        type: {
          name: "Composite",
          className: "Project"
        }
      }
    }
  }
};

export const GetCardProjectOKResponse: msRest.CompositeMapper = {
  serializedName: "GetCardProjectOKResponse",
  type: {
    name: "Composite",
    className: "GetCardProjectOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "GetCardProjectOKResponseData"
        }
      }
    }
  }
};

export const GetProjectWorkTypesOKResponseData: msRest.CompositeMapper = {
  serializedName: "GetProjectWorkTypesOKResponse_data",
  type: {
    name: "Composite",
    className: "GetProjectWorkTypesOKResponseData",
    modelProperties: {
      workTypes: {
        serializedName: "work_types",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "ProjectWorkType"
            }
          }
        }
      }
    }
  }
};

export const GetProjectWorkTypesOKResponse: msRest.CompositeMapper = {
  serializedName: "GetProjectWorkTypesOKResponse",
  type: {
    name: "Composite",
    className: "GetProjectWorkTypesOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "GetProjectWorkTypesOKResponseData"
        }
      }
    }
  }
};

export const PostSubmitCardWorkOKResponseData: msRest.CompositeMapper = {
  serializedName: "PostSubmitCardWorkOKResponse_data",
  type: {
    name: "Composite",
    className: "PostSubmitCardWorkOKResponseData",
    modelProperties: {
      workItem: {
        serializedName: "work_item",
        type: {
          name: "Composite",
          className: "ProjectWorkType"
        }
      }
    }
  }
};

export const PostSubmitCardWorkOKResponse: msRest.CompositeMapper = {
  serializedName: "PostSubmitCardWorkOKResponse",
  type: {
    name: "Composite",
    className: "PostSubmitCardWorkOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "PostSubmitCardWorkOKResponseData"
        }
      }
    }
  }
};

export const PostInvoiceCreatedResponseData: msRest.CompositeMapper = {
  serializedName: "PostInvoiceCreatedResponse_data",
  type: {
    name: "Composite",
    className: "PostInvoiceCreatedResponseData",
    modelProperties: {
      invoice: {
        serializedName: "invoice",
        type: {
          name: "Composite",
          className: "Invoice"
        }
      }
    }
  }
};

export const PostInvoiceCreatedResponse: msRest.CompositeMapper = {
  serializedName: "PostInvoiceCreatedResponse",
  type: {
    name: "Composite",
    className: "PostInvoiceCreatedResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "PostInvoiceCreatedResponseData"
        }
      }
    }
  }
};

export const GetMyInvoiceOKResponseData: msRest.CompositeMapper = {
  serializedName: "GetMyInvoiceOKResponse_data",
  type: {
    name: "Composite",
    className: "GetMyInvoiceOKResponseData",
    modelProperties: {
      invoice: {
        serializedName: "invoice",
        type: {
          name: "Composite",
          className: "Invoice"
        }
      }
    }
  }
};

export const GetMyInvoiceOKResponse: msRest.CompositeMapper = {
  serializedName: "GetMyInvoiceOKResponse",
  type: {
    name: "Composite",
    className: "GetMyInvoiceOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "GetMyInvoiceOKResponseData"
        }
      }
    }
  }
};

export const GetMyActiveInvoicesOKResponseData: msRest.CompositeMapper = {
  serializedName: "GetMyActiveInvoicesOKResponse_data",
  type: {
    name: "Composite",
    className: "GetMyActiveInvoicesOKResponseData",
    modelProperties: {
      invoices: {
        serializedName: "invoices",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Invoice"
            }
          }
        }
      }
    }
  }
};

export const GetMyActiveInvoicesOKResponse: msRest.CompositeMapper = {
  serializedName: "GetMyActiveInvoicesOKResponse",
  type: {
    name: "Composite",
    className: "GetMyActiveInvoicesOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "GetMyActiveInvoicesOKResponseData"
        }
      }
    }
  }
};

export const GetMyFinishedInvoicesOKResponseData: msRest.CompositeMapper = {
  serializedName: "GetMyFinishedInvoicesOKResponse_data",
  type: {
    name: "Composite",
    className: "GetMyFinishedInvoicesOKResponseData",
    modelProperties: {
      invoices: {
        serializedName: "invoices",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Invoice"
            }
          }
        }
      }
    }
  }
};

export const GetMyFinishedInvoicesOKResponse: msRest.CompositeMapper = {
  serializedName: "GetMyFinishedInvoicesOKResponse",
  type: {
    name: "Composite",
    className: "GetMyFinishedInvoicesOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "GetMyFinishedInvoicesOKResponseData"
        }
      }
    }
  }
};

export const PatchMyInvoiceOKResponseData: msRest.CompositeMapper = {
  serializedName: "PatchMyInvoiceOKResponse_data",
  type: {
    name: "Composite",
    className: "PatchMyInvoiceOKResponseData",
    modelProperties: {
      invoices: {
        serializedName: "invoices",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Invoice"
            }
          }
        }
      }
    }
  }
};

export const PatchMyInvoiceOKResponse: msRest.CompositeMapper = {
  serializedName: "PatchMyInvoiceOKResponse",
  type: {
    name: "Composite",
    className: "PatchMyInvoiceOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "PatchMyInvoiceOKResponseData"
        }
      }
    }
  }
};

export const GetMyBalancesOKResponseData: msRest.CompositeMapper = {
  serializedName: "GetMyBalancesOKResponse_data",
  type: {
    name: "Composite",
    className: "GetMyBalancesOKResponseData",
    modelProperties: {
      balances: {
        serializedName: "balances",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "UserBalance"
            }
          }
        }
      }
    }
  }
};

export const GetMyBalancesOKResponse: msRest.CompositeMapper = {
  serializedName: "GetMyBalancesOKResponse",
  type: {
    name: "Composite",
    className: "GetMyBalancesOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "GetMyBalancesOKResponseData"
        }
      }
    }
  }
};

export const GetMySettingOKResponseData: msRest.CompositeMapper = {
  serializedName: "GetMySettingOKResponse_data",
  type: {
    name: "Composite",
    className: "GetMySettingOKResponseData",
    modelProperties: {
      setting: {
        serializedName: "setting",
        type: {
          name: "Composite",
          className: "UserSetting"
        }
      }
    }
  }
};

export const GetMySettingOKResponse: msRest.CompositeMapper = {
  serializedName: "GetMySettingOKResponse",
  type: {
    name: "Composite",
    className: "GetMySettingOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "GetMySettingOKResponseData"
        }
      }
    }
  }
};

export const SetMySettingOKResponseData: msRest.CompositeMapper = {
  serializedName: "SetMySettingOKResponse_data",
  type: {
    name: "Composite",
    className: "SetMySettingOKResponseData",
    modelProperties: {
      setting: {
        serializedName: "setting",
        type: {
          name: "Composite",
          className: "UserSetting"
        }
      }
    }
  }
};

export const SetMySettingOKResponse: msRest.CompositeMapper = {
  serializedName: "SetMySettingOKResponse",
  type: {
    name: "Composite",
    className: "SetMySettingOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "SetMySettingOKResponseData"
        }
      }
    }
  }
};

export const GetMyLibraryProjectsOKResponseData: msRest.CompositeMapper = {
  serializedName: "GetMyLibraryProjectsOKResponse_data",
  type: {
    name: "Composite",
    className: "GetMyLibraryProjectsOKResponseData",
    modelProperties: {
      libraryProjects: {
        serializedName: "library_projects",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "LibraryItem"
            }
          }
        }
      }
    }
  }
};

export const GetMyLibraryProjectsOKResponse: msRest.CompositeMapper = {
  serializedName: "GetMyLibraryProjectsOKResponse",
  type: {
    name: "Composite",
    className: "GetMyLibraryProjectsOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "GetMyLibraryProjectsOKResponseData"
        }
      }
    }
  }
};

export const AddProjectToMyLibraryCreatedResponseData: msRest.CompositeMapper = {
  serializedName: "AddProjectToMyLibraryCreatedResponse_data",
  type: {
    name: "Composite",
    className: "AddProjectToMyLibraryCreatedResponseData",
    modelProperties: {
      libraryProject: {
        serializedName: "library_project",
        type: {
          name: "Composite",
          className: "LibraryItem"
        }
      }
    }
  }
};

export const AddProjectToMyLibraryCreatedResponse: msRest.CompositeMapper = {
  serializedName: "AddProjectToMyLibraryCreatedResponse",
  type: {
    name: "Composite",
    className: "AddProjectToMyLibraryCreatedResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "AddProjectToMyLibraryCreatedResponseData"
        }
      }
    }
  }
};

export const RemoveProjectFromMyLibraryOKResponseData: msRest.CompositeMapper = {
  serializedName: "RemoveProjectFromMyLibraryOKResponse_data",
  type: {
    name: "Composite",
    className: "RemoveProjectFromMyLibraryOKResponseData",
    modelProperties: {
      libraryProject: {
        serializedName: "library_project",
        type: {
          name: "Composite",
          className: "LibraryItem"
        }
      }
    }
  }
};

export const RemoveProjectFromMyLibraryOKResponse: msRest.CompositeMapper = {
  serializedName: "RemoveProjectFromMyLibraryOKResponse",
  type: {
    name: "Composite",
    className: "RemoveProjectFromMyLibraryOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "RemoveProjectFromMyLibraryOKResponseData"
        }
      }
    }
  }
};

export const GetMyLibraryProjectStatusOKResponseDataStatus: msRest.CompositeMapper = {
  serializedName: "GetMyLibraryProjectStatusOKResponse_data_status",
  type: {
    name: "Composite",
    className: "GetMyLibraryProjectStatusOKResponseDataStatus",
    modelProperties: {
      inLibrary: {
        serializedName: "in_library",
        type: {
          name: "Boolean"
        }
      }
    }
  }
};

export const GetMyLibraryProjectStatusOKResponseData: msRest.CompositeMapper = {
  serializedName: "GetMyLibraryProjectStatusOKResponse_data",
  type: {
    name: "Composite",
    className: "GetMyLibraryProjectStatusOKResponseData",
    modelProperties: {
      status: {
        serializedName: "status",
        type: {
          name: "Composite",
          className: "GetMyLibraryProjectStatusOKResponseDataStatus"
        }
      }
    }
  }
};

export const GetMyLibraryProjectStatusOKResponse: msRest.CompositeMapper = {
  serializedName: "GetMyLibraryProjectStatusOKResponse",
  type: {
    name: "Composite",
    className: "GetMyLibraryProjectStatusOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "GetMyLibraryProjectStatusOKResponseData"
        }
      }
    }
  }
};

export const GetMeOKResponseData: msRest.CompositeMapper = {
  serializedName: "GetMeOKResponse_data",
  type: {
    name: "Composite",
    className: "GetMeOKResponseData",
    modelProperties: {
      me: {
        serializedName: "me",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "User"
            }
          }
        }
      }
    }
  }
};

export const GetMeOKResponse: msRest.CompositeMapper = {
  serializedName: "GetMeOKResponse",
  type: {
    name: "Composite",
    className: "GetMeOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "GetMeOKResponseData"
        }
      }
    }
  }
};

export const GetUserOKResponseData: msRest.CompositeMapper = {
  serializedName: "GetUserOKResponse_data",
  type: {
    name: "Composite",
    className: "GetUserOKResponseData",
    modelProperties: {
      user: {
        serializedName: "user",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "User"
            }
          }
        }
      }
    }
  }
};

export const GetUserOKResponse: msRest.CompositeMapper = {
  serializedName: "GetUserOKResponse",
  type: {
    name: "Composite",
    className: "GetUserOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "GetUserOKResponseData"
        }
      }
    }
  }
};

export const LoginViaFacebookOKResponseData: msRest.CompositeMapper = {
  serializedName: "LoginViaFacebookOKResponse_data",
  type: {
    name: "Composite",
    className: "LoginViaFacebookOKResponseData",
    modelProperties: {
      token: {
        serializedName: "token",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const LoginViaFacebookOKResponse: msRest.CompositeMapper = {
  serializedName: "LoginViaFacebookOKResponse",
  type: {
    name: "Composite",
    className: "LoginViaFacebookOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "LoginViaFacebookOKResponseData"
        }
      }
    }
  }
};

export const LoginViaGoogleOKResponseData: msRest.CompositeMapper = {
  serializedName: "LoginViaGoogleOKResponse_data",
  type: {
    name: "Composite",
    className: "LoginViaGoogleOKResponseData",
    modelProperties: {
      token: {
        serializedName: "token",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const LoginViaGoogleOKResponse: msRest.CompositeMapper = {
  serializedName: "LoginViaGoogleOKResponse",
  type: {
    name: "Composite",
    className: "LoginViaGoogleOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "LoginViaGoogleOKResponseData"
        }
      }
    }
  }
};

export const GetMyEntityPermissionsOKResponseData: msRest.CompositeMapper = {
  serializedName: "GetMyEntityPermissionsOKResponse_data",
  type: {
    name: "Composite",
    className: "GetMyEntityPermissionsOKResponseData",
    modelProperties: {
      permissions: {
        serializedName: "permissions",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const GetMyEntityPermissionsOKResponse: msRest.CompositeMapper = {
  serializedName: "GetMyEntityPermissionsOKResponse",
  type: {
    name: "Composite",
    className: "GetMyEntityPermissionsOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "GetMyEntityPermissionsOKResponseData"
        }
      }
    }
  }
};

export const GetNewestProjectsOKResponseData: msRest.CompositeMapper = {
  serializedName: "GetNewestProjectsOKResponse_data",
  type: {
    name: "Composite",
    className: "GetNewestProjectsOKResponseData",
    modelProperties: {
      projects: {
        serializedName: "projects",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Project"
            }
          }
        }
      }
    }
  }
};

export const GetNewestProjectsOKResponse: msRest.CompositeMapper = {
  serializedName: "GetNewestProjectsOKResponse",
  type: {
    name: "Composite",
    className: "GetNewestProjectsOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "GetNewestProjectsOKResponseData"
        }
      }
    }
  }
};

export const GetRandomProjectsOKResponseData: msRest.CompositeMapper = {
  serializedName: "GetRandomProjectsOKResponse_data",
  type: {
    name: "Composite",
    className: "GetRandomProjectsOKResponseData",
    modelProperties: {
      projects: {
        serializedName: "projects",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Project"
            }
          }
        }
      }
    }
  }
};

export const GetRandomProjectsOKResponse: msRest.CompositeMapper = {
  serializedName: "GetRandomProjectsOKResponse",
  type: {
    name: "Composite",
    className: "GetRandomProjectsOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "GetRandomProjectsOKResponseData"
        }
      }
    }
  }
};

export const GetProjectProductsOKResponseData: msRest.CompositeMapper = {
  serializedName: "GetProjectProductsOKResponse_data",
  type: {
    name: "Composite",
    className: "GetProjectProductsOKResponseData",
    modelProperties: {
      products: {
        serializedName: "products",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "ProjectProduct"
            }
          }
        }
      }
    }
  }
};

export const GetProjectProductsOKResponse: msRest.CompositeMapper = {
  serializedName: "GetProjectProductsOKResponse",
  type: {
    name: "Composite",
    className: "GetProjectProductsOKResponse",
    modelProperties: {
      data: {
        serializedName: "data",
        type: {
          name: "Composite",
          className: "GetProjectProductsOKResponseData"
        }
      }
    }
  }
};
