/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "./models";

const packageName = "";
const packageVersion = "";

export class SupportHubApiContext extends msRest.ServiceClient {
  entityType: string;
  currencyType?: Models.CurrencyType4;

  /**
   * Initializes a new instance of the SupportHubApiContext class.
   * @param entityType Possible values include: 'ProjectCategory', 'Project', 'Board', 'Card',
   * 'BacklogItem', 'UserBalance', 'User', 'ProjectProductPurchase', 'BoardColumn'
   * @param [options] The parameter options
   */
  constructor(entityType: string, options?: Models.SupportHubApiOptions) {
    if (entityType == undefined) {
      throw new Error("'entityType' cannot be null.");
    }

    if (!options) {
      options = {};
    }

    if (!options.userAgent) {
      const defaultUserAgent = msRest.getDefaultUserAgentValue();
      options.userAgent = `${packageName}/${packageVersion} ${defaultUserAgent}`;
    }

    super(undefined, options);

    this.baseUri = options.baseUri || this.baseUri || "http://api.gitcom.org/api/v1";
    this.requestContentType = "application/json; charset=utf-8";
    this.entityType = entityType;
    if (options.currencyType !== null && options.currencyType !== undefined) {
      this.currencyType = options.currencyType;
    }
  }
}
